name: cd

#on:
#  workflow_run:
#    workflows: ["ci"]
#    types:
#      - completed

on: [push, pull_request]

jobs:
  release-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update; sudo apt install libsdl2-dev pkg-config libx11-dev libasound2-dev libudev-dev
      
      - name: Pull cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: build-wasm-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Setup WASM toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - name: Build web-release
        run: |
          trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"
      
      - name: Deploy web-release
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist