name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instsll dependencies
        run: sudo apt update; sudo apt install libsdl2-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: test-ubuntu-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo test --all